server:
  port: 8080

springdoc:
  swagger-ui:
    path: /swagger-ui

spring:
  application:
    name: code_elevate

  data:
    mongodb:
      uri: ${MONGODB_URI}
      database: ${MONGODB_DATABASE}

    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}
